version: '3.8'

services:
  cf-clearance-api:
    build: .
    expose:
      - "8000"
    environment:
      - PYTHONUNBUFFERED=1
      - MAX_CONCURRENT_REQUESTS=3
      - CHROME_HEADLESS=true
      - TIMEOUT_DEFAULT=45
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 60s
      timeout: 15s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 3.2G
          cpus: '1.8'
        reservations:
          memory: 512M
          cpus: '0.3'
    shm_size: 512mb

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.zsnow.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - cf-clearance-api
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.2'

